[package]
name = "hexenzsene-chess"
version = "0.2.1"
edition = "2024"

[profile.release-with-debug]
inherits = "release"
debug = true

[profile.test] 
opt-level = 3

[profile.release]
opt-level = 3
lto = true 
codegen-units = 1

[profile.bench]
inherits = "release"
opt-level = 3
lto = true
codegen-units = 1